version: "3"

services:
  user-service-postgres-testing:
    container_name: user-service-postgres-testing
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users