[tool.poetry]
name = "ct-iot-user-service"
version = "0.1.0"
description = ""
authors = ["Darryl Morton"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
httpx = "^0.25.0"
trio = "^0.22.2"
ruff = "^0.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
include = ["*.py", "*.pyi", "**/prproject.toml", "*.ipynb"]
line-length = 100  # defaults to 88 like black
target-version = "py310"  # the python version to target, useful when considering code upgrades, defaults to "py310"

select = [
  "B",   # black
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade,
#  "I",   # isort
]